import * as React from 'react';
import type { StoryProps } from '@ladle/react';
export declare const AllowOverlap: React.FC<StoryProps>;
export declare const AnimatingContainer: React.FC<StoryProps>;
export declare const Basic: React.FC<StoryProps>;
export declare const WithLimit: React.FC<StoryProps>;
export declare const BasicWithBorder: React.FC<StoryProps>;
export declare const BigSteps: React.FC<StoryProps>;
export declare const Disabled: React.FC<StoryProps>;
export declare const DownDirection: React.FC<StoryProps>;
export declare const Labeled: React.FC<StoryProps>;
export declare const LabeledTwoThumbs: React.FC<StoryProps>;
export declare const LeftDirection: React.FC<StoryProps>;
export declare const Marks: React.FC<StoryProps>;
export declare const MarksDynamic: React.FC<StoryProps>;
export declare const MarksVertical: React.FC<StoryProps>;
export declare const MergingLabels: React.FC<StoryProps>;
export declare const MergingLabelsCustom: React.FC<StoryProps>;
export declare const MergingLabelsSkinny: React.FC<StoryProps>;
export declare const MultipleThumbs: React.FC<StoryProps>;
export declare const MultipleThumbsWithDraggableTrack: React.FC<StoryProps>;
export declare const OnFinalChangeEvent: React.FC<StoryProps>;
export declare const SuperSimple: React.FC<StoryProps>;
export declare const TwoThumbs: React.FC<StoryProps>;
export declare const TwoThumbsWithDraggableTrack: React.FC<StoryProps>;
export declare const TwoThumbsWithDraggableTrackAndDownDirection: React.FC<StoryProps>;
export declare const UpDirection: React.FC<StoryProps>;
